In [11]:
import numpy as np

In [13]:
#q2
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#q3
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
#q3
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [16]:
#q4
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [17]:
#q5
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [18]:
#q6
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#q7
np.random.rand(25)

array([0.76047125, 0.09853293, 0.46264584, 0.85768226, 0.39557497,
       0.29241873, 0.44432248, 0.86150862, 0.63783988, 0.30499553,
       0.49712905, 0.48108312, 0.97679978, 0.55816104, 0.26507209,
       0.39222922, 0.17958354, 0.1289774 , 0.35593673, 0.42866102,
       0.68686115, 0.3790105 , 0.9953506 , 0.41817504, 0.32213841])

In [20]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [21]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [22]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
# 14 feb
mat=np.arange(1,26).reshape(5,5)

In [24]:
mat[2:5 , 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [25]:
mat[3:4 , 4:5]

array([[20]])

In [26]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [27]:
mat[4:5]

array([[21, 22, 23, 24, 25]])

In [28]:
mat[0:3 , 1:2]

array([[ 2],
       [ 7],
       [12]])

In [29]:
np.std(mat)

7.211102550927978

In [30]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [31]:
oneD=np.arange(0,12)
oneD

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
twoD=np.arange(0,12).reshape(3,4)
twoD.dtype

dtype('int32')

In [33]:
threeD=np.arange(0,12).reshape(3,2,2)
threeD.shape

(3, 2, 2)

In [34]:
np.empty((3))

array([1., 1., 1.])

In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.ones(15).reshape(3,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
maths=np.random.randint(0,100,20)
maths

array([74, 22, 64, 25, 94, 22, 61, 15, 38, 67, 27,  0, 88, 32, 28, 94, 16,
       44,  9, 25])

In [39]:
np.sort(maths)

array([ 0,  9, 15, 16, 22, 22, 25, 25, 27, 28, 32, 38, 44, 61, 64, 67, 74,
       88, 94, 94])

In [40]:
np.flip(maths)

array([25,  9, 44, 16, 94, 28, 32, 88,  0, 27, 67, 38, 15, 61, 22, 94, 25,
       64, 22, 74])

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.eye(5).reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [43]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
#q19
#[1,0,2,0,0,4,0,8]
#0,2,5,7

np.nonzero([1,0,2,0,0,4,0,8])

(array([0, 2, 5, 7], dtype=int64),)

In [46]:
a=np.ones((5,5))
b=a[1:4,1:4]
b


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
#q20
a=np.ones((10,10))
a[1:9,1:9]=0
a


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [48]:
#q21
a=np.ones((8,8))
a[:,0:1]


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [49]:

a[0:9:2,0:1]=0
a

array([[0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [50]:
a[::2,:]=0
#a[::2,::2]

In [51]:
a[:,:]

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
a[::2,::2]=0
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [53]:
#q22
a=np.random.randint(0,10,(3,3))
b=np.random.randint(0,10,(3,3))
print("matrix1",a)
print("matrix2",b)

add=a+b
print("add",a)

m=a@b
print("muliply",m)

s=a-b
print("sub",s)

matrix1 [[9 3 6]
 [6 2 8]
 [9 8 4]]
matrix2 [[6 9 9]
 [0 5 4]
 [6 3 0]]
add [[9 3 6]
 [6 2 8]
 [9 8 4]]
muliply [[ 90 114  93]
 [ 84  88  62]
 [ 78 133 113]]
sub [[ 3 -6 -3]
 [ 6 -3  4]
 [ 3  5  4]]


In [54]:
mat=np.arange(0,25).reshape(5,5)
mat[0::2,0::2]=0
mat[1::2,1::2]=0
mat

array([[ 0,  1,  0,  3,  0],
       [ 5,  0,  7,  0,  9],
       [ 0, 11,  0, 13,  0],
       [15,  0, 17,  0, 19],
       [ 0, 21,  0, 23,  0]])

In [55]:
#q21
    mat=np.ones((8,8))
mat[0::2,0::2]=0
mat[1::2,1::2]=0
mat

IndentationError: unexpected indent (1656189294.py, line 2)

In [4]:
import pandas as pd
import numpy as np

In [5]:
labels=['x','y','z']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,'b':20,'c':30}
d

{'a': 10, 'b': 20, 'c': 30}

In [6]:
#STUDENT MARKS
marks=pd.Series([30,39,40],index=["PYTHON","DBMS","DSA"])
marks

PYTHON    30
DBMS      39
DSA       40
dtype: int64

In [14]:
marks.keys()

Index(['PYTHON', 'DBMS', 'DSA'], dtype='object')

In [15]:
marks.values

array([30, 39, 40], dtype=int64)

In [20]:
d={"name":'janvi',"email":'abc@gmail.com',"course":'bca'}
pd.Series(d)

name              janvi
email     abc@gmail.com
course              bca
dtype: object

In [21]:
d.keys()

dict_keys(['name', 'email', 'course'])

In [29]:
d.values

<function dict.values>

In [59]:
from numpy.random import randn
import pandas as pd
import numpy as np

df=pd.DataFrame(np.random.randint(1,100,(4,3)),index=['riya','siya','tiya','jiya'],columns=['python','data science','dsa'])
df

python  data science  dsa
riya      51            43    2
siya      97            97    7
tiya      63            12   18
jiya      84            52   68

In [60]:
df['python']

riya    51
siya    97
tiya    63
jiya    84
Name: python, dtype: int32

In [61]:
df.loc['jiya']

python          84
data science    52
dsa             68
Name: jiya, dtype: int32

In [62]:
df['names']=['tina','sina','pina','lina']
df

python  data science  dsa names
riya      51            43    2  tina
siya      97            97    7  sina
tiya      63            12   18  pina
jiya      84            52   68  lina

In [63]:
df.set_index('names')

python  data science  dsa
names                           
tina       51            43    2
sina       97            97    7
pina       63            12   18
lina       84            52   68

In [64]:
df['total']=df['python']+df['data science']+df['dsa']
df

python  data science  dsa names  total
riya      51            43    2  tina     96
siya      97            97    7  sina    201
tiya      63            12   18  pina     93
jiya      84            52   68  lina    204

In [65]:
df.drop('names',axis=1)

python  data science  dsa  total
riya      51            43    2     96
siya      97            97    7    201
tiya      63            12   18     93
jiya      84            52   68    204

In [66]:
df.drop['names',axis=1,inplace=True]

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (597073910.py, line 1)

In [67]:
df

python  data science  dsa names  total
riya      51            43    2  tina     96
siya      97            97    7  sina    201
tiya      63            12   18  pina     93
jiya      84            52   68  lina    204

In [68]:
df1=pd.read_csv('data.csv')
df1

1 abc 345
0   2 fgf 567
1  3 dfk 6778

In [69]:
#q1
df=pd.DataFrame(np.random.randint(1,100,(3,5)),index=['productid','product name','product price'],columns=['element1','element2','element3','element4','element5'])
df

element1  element2  element3  element4  element5
productid             4        62        92        48        25
product name         51         1        70        20        72
product price        37        43        47         5         8

In [70]:
#q3
df.loc[['productid','product price']]

element1  element2  element3  element4  element5
productid             4        62        92        48        25
product price        37        43        47         5         8

In [71]:
#q3
df.iloc[2]

element1    37
element2    43
element3    47
element4     5
element5     8
Name: product price, dtype: int32

In [72]:
#q4
df.loc['productid':]

element1  element2  element3  element4  element5
productid             4        62        92        48        25
product name         51         1        70        20        72
product price        37        43        47         5         8

In [73]:
#q5
df.iloc[2]

element1    37
element2    43
element3    47
element4     5
element5     8
Name: product price, dtype: int32

In [74]:
#q1
df=pd.DataFrame(np.random.randint(1,100,(5,3)),index=['element1','element2','element3','element4','element5'],columns=['productid','productname','productprice'])
df


productid  productname  productprice
element1         40           77            19
element2         60           91            35
element3         44           39            43
element4         96           38            14
element5         73           98            77

In [75]:
#q3(loc)
df.loc[['element2','element4']]

productid  productname  productprice
element2         60           91            35
element4         96           38            14

In [76]:
#Q3(ILOC)
df.iloc[3]

productid       96
productname     38
productprice    14
Name: element4, dtype: int32

In [77]:
#q4
df.loc['2':]

productid  productname  productprice
element1         40           77            19
element2         60           91            35
element3         44           39            43
element4         96           38            14
element5         73           98            77

In [78]:
#q5
df.iloc[2]

productid       44
productname     39
productprice    43
Name: element3, dtype: int32

# q5
df.iloc[2,2]
df.loc['element1':,['productprice']]

In [79]:
#q5
df.iloc[2,2] 
df.loc['element1':,['productprice']]

productprice
element1            19
element2            35
element3            43
element4            14
element5            77

In [80]:
#q6


In [81]:
#q7


In [82]:
#q8
df=pd.DataFrame(np.random.randint(1,100,(4,3)),index=['riya','siya','tiya','jiya'],columns=['python','data science','dsa'])
df

python  data science  dsa
riya      57            59   37
siya      68            38   42
tiya      54            51   58
jiya      35            69   88

In [83]:
#q8
df['python']>40

riya     True
siya     True
tiya     True
jiya    False
Name: python, dtype: bool

In [84]:
#q8
df.loc[df['python']>40,'python']

riya    57
siya    68
tiya    54
Name: python, dtype: int32

In [85]:
#q9
df+2

python  data science  dsa
riya      59            61   39
siya      70            40   44
tiya      56            53   60
jiya      37            71   90

In [86]:
df

python  data science  dsa
riya      57            59   37
siya      68            38   42
tiya      54            51   58
jiya      35            69   88

In [87]:
#q9
df2=(df+2)
df

python  data science  dsa
riya      57            59   37
siya      68            38   42
tiya      54            51   58
jiya      35            69   88

In [88]:
#q9
df3=(df+50)
df3

python  data science  dsa
riya     107           109   87
siya     118            88   92
tiya     104           101  108
jiya      85           119  138

In [89]:
#q9
df2[df2>100]=100
df2

python  data science  dsa
riya      59            61   39
siya      70            40   44
tiya      56            53   60
jiya      37            71   90

In [90]:
#q10
#AND #OR

In [91]:
df3

python  data science  dsa
riya     107           109   87
siya     118            88   92
tiya     104           101  108
jiya      85           119  138

In [92]:
#q10
df3[(df3['python']>80) & (df['data science']>105)]


Empty DataFrame
Columns: [python, data science, dsa]
Index: []

In [93]:
#q11
df[df.index.str.startswith('s')]

python  data science  dsa
siya      68            38   42

In [94]:
#q12
df[df.index.str.endswith('a')]
df

python  data science  dsa
riya      57            59   37
siya      68            38   42
tiya      54            51   58
jiya      35            69   88

In [95]:
#q13
df['total']=df['python']+df['data science']+df['dsa']
df

python  data science  dsa  total
riya      57            59   37    153
siya      68            38   42    148
tiya      54            51   58    163
jiya      35            69   88    192

In [96]:
#q13
df['precentage']=((df['python']+df['data science']+df['dsa']))/400*100
df

python  data science  dsa  total  precentage
riya      57            59   37    153       38.25
siya      68            38   42    148       37.00
tiya      54            51   58    163       40.75
jiya      35            69   88    192       48.00

In [97]:
#q14
df["result"]=df['precentage']>30
df

python  data science  dsa  total  precentage  result
riya      57            59   37    153       38.25    True
siya      68            38   42    148       37.00    True
tiya      54            51   58    163       40.75    True
jiya      35            69   88    192       48.00    True

In [98]:
#q14
df.loc[df['precentage']>30,"result"]="pass"
df

python  data science  dsa  total  precentage result
riya      57            59   37    153       38.25   pass
siya      68            38   42    148       37.00   pass
tiya      54            51   58    163       40.75   pass
jiya      35            69   88    192       48.00   pass

In [99]:
#q14
df.loc[df['precentage']<20,"result"]="fail"
df

python  data science  dsa  total  precentage result
riya      57            59   37    153       38.25   pass
siya      68            38   42    148       37.00   pass
tiya      54            51   58    163       40.75   pass
jiya      35            69   88    192       48.00   pass

In [100]:
#Q14
df['result']=np.where(df['precentage']<40,"fail","pass")
df

python  data science  dsa  total  precentage result
riya      57            59   37    153       38.25   fail
siya      68            38   42    148       37.00   fail
tiya      54            51   58    163       40.75   pass
jiya      35            69   88    192       48.00   pass

In [114]:
#q15
df['grade']=np.where(df['precentage']>10,"E",np.where(df['precentage']>20,"d",np.where(df['precentage']>30,"C",np.where(df['precentage']>40,"B",np.where(df['precentage']>50,"A","F")))))

In [112]:
df

python  data science  dsa  total  precentage result grade
riya      57            59   37    153       38.25   fail     E
siya      68            38   42    148       37.00   fail     E
tiya      54            51   58    163       40.75   pass     E
jiya      35            69   88    192       48.00   pass     E

In [118]:
#q15
df.loc[df['precentage']>10,'grade']='E'
df.loc[df['precentage']>20,'grade']='D'
df.loc[df['precentage']>30,'grade']='C'
df.loc[df['precentage']>40,'grade']='B'
df.loc[df['precentage']>50,'grade']='A'
df

python  data science  dsa  total  precentage result grade
riya      57            59   37    153       38.25   fail     C
siya      68            38   42    148       37.00   fail     C
tiya      54            51   58    163       40.75   pass     B
jiya      35            69   88    192       48.00   pass     B

In [119]:
#q16
df.describe()

python  data science       dsa       total  precentage
count   4.000000      4.000000   4.00000    4.000000    4.000000
mean   53.500000     54.250000  56.25000  164.000000   41.000000
std    13.723459     13.098982  22.98369   19.680786    4.920196
min    35.000000     38.000000  37.00000  148.000000   37.000000
25%    49.250000     47.750000  40.75000  151.750000   37.937500
50%    55.500000     55.000000  50.00000  158.000000   39.500000
75%    59.750000     61.500000  65.50000  170.250000   42.562500
max    68.000000     69.000000  88.00000  192.000000   48.000000